mundschenk-at/php-typography

- .scrutinizer.yml
- .scrutinizer/phpcs-run
- phpcs.xml
Using custom coding standards on Scrutinizer
> Scrutinizer fixes

- src/class-php-typography.php
- src/fixes/node-fixes/class-process-words-fix.php
- src/fixes/token-fixes/class-hyphenate-compounds-fix.php
- src/fixes/token-fixes/class-hyphenate-fix.php
- src/fixes/token-fixes/class-wrap-urls-fix.php
- src/hyphenator/class-cache.php
- tests/benchmarks/class-hyphenator-cache-bench.php
- tests/class-php-typography-test.php
- tests/fixes/token-fixes/class-hyphenate-compounds-fix-test.php
- tests/fixes/token-fixes/class-hyphenate-fix-test.php
- tests/fixes/token-fixes/class-wrap-urls-fix-test.php
- tests/hyphenator/class-cache-test.php
Improve downstream usability of the hyphenator cache
> Hyphenator cache improvements

- composer.json
- src/class-dom.php
- src/class-settings.php
- tests/class-dom-test.php
- tests/class-php-typography-test.php
- tests/class-settings-test.php
- tests/fixes/node-fixes/class-abstract-node-fix-test.php
- tests/fixes/node-fixes/class-classes-dependent-fix-test.php
- tests/fixes/node-fixes/class-dash-spacing-fix-test.php
- tests/fixes/token-fixes/class-abstract-token-fix-test.php
- tests/fixes/token-fixes/class-hyphenate-compounds-fix-test.php
- tests/fixes/token-fixes/class-hyphenate-fix-test.php
- tests/fixes/token-fixes/class-wrap-emails-fix-test.php
- tests/fixes/token-fixes/class-wrap-hard-hyphens-fix-test.php
- tests/fixes/token-fixes/class-wrap-urls-fix-test.php
> Deprecate Settings::inappropriate_tags and Settings::self_closing_tags

- src/class-settings.php
- tests/class-settings-test.php
> Use all relevant properties in the settings hash

- src/fixes/node-fixes/class-dewidow-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-dewidow-fix-test.php
Honor narrow spaces when dewidowing multiple words. Fixes #34.
> Honor narrow spaces during dewidowing

- src/fixes/node-fixes/class-abstract-node-fix.php
- src/fixes/node-fixes/class-french-punctuation-spacing-fix.php
- src/fixes/node-fixes/class-single-character-word-spacing-fix.php
- src/fixes/node-fixes/class-smart-quotes-fix.php
- src/fixes/node-fixes/class-style-hanging-punctuation-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-abstract-node-fix-test.php
- tests/fixes/node-fixes/class-smart-quotes-fix-test.php
> Fix French quote bug

- composer.json
- tests/benchmarks/class-functions-bench.php
- tests/benchmarks/class-multibyte-switching-bench.php
Benchmark results from PHP 7.2 with opcache. Relative PHP 5.6 results are similar, though everything takes a bit longer.
```13 subjects, 156 iterations, 15,600 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 67.925 [18,934.579 18,934.732] 76.860 (μs)
⅀T: 2,953,794.250μs μSD/r 161.367μs μRSD/r: 2.429%
suite: 133c9d19c6bb492015223463715d427d99ba5fe6, date: 2017-12-17, stime: 11:31:39
+---------------------------+-----------------------------+--------+----------------------------------------------------+------+-----+------------+---------+---------+---------+---------+-------+--------+-----------+
| benchmark                 | subject                     | groups | params                                             | revs | its | mem_peak   | best    | mean    | mode    | …
```
> Benchmarks: multi-byte switching overhead vs. mb_* performance

- .scrutinizer.yml
- .travis.yml
- README.md
- Add badges to README.md
- Generate coverage information in Travis and send it to Scrutinizer
> Add badges & coverage information

- src/class-php-typography.php
- tests/class-php-typography-test.php
> Inject body classes

- src/class-settings.php
- tests/class-php-typography-test.php
- tests/class-php-typography-testcase.php
- tests/class-settings-test.php
- Provide better defaults
- Simplify Settings initialization
> Better defaults

- src/fixes/node-fixes/class-smart-marks-fix.php
- tests/fixes/node-fixes/class-smart-marks-fix-test.php
@mundschenk-at requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/mundschenk-at/php-typography/
> Scrutinizer Auto-Fixes

- .travis.yml
- New Travis build script
- phpcs is checked in Scrutinizer instead
> New Travis build script

- CHANGELOG.md
- composer.json
- src/class-php-typography.php
- src/class-re.php
- src/fixes/node-fixes/class-simple-style-fix.php
- src/fixes/node-fixes/class-smart-exponents-fix.php
- src/fixes/node-fixes/class-smart-fractions-fix.php
- src/fixes/node-fixes/class-smart-ordinal-suffix-fix.php
- src/fixes/node-fixes/class-style-hanging-punctuation-fix.php
- src/fixes/node-fixes/class-style-initial-quotes-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-node-fix-testcase.php
- tests/fixes/node-fixes/class-simple-style-fix-test.php
- tests/fixes/node-fixes/class-smart-exponents-fix-test.php
- tests/fixes/node-fixes/class-smart-fractions-fix-test.php
- tests/fixes/node-fixes/class-smart-ordinal-suffix-fix-test.php
- tests/fixes/node-fixes/class-style-ampersands-fix-test.php
- tests/fixes/node-fixes/class-style-caps-fix-test.php
- tests/fixes/node-fixes/class-style-hanging-punctuation-fix-test.php
- tests/fixes/node-fixes/class-style-initial-quotes-fix-test.php
- tests/fixes/node-fixes/class-style-numbers-fix-test.php
Fixes standalone < and > being silently dropped in the HTML injection phase.
> Release 6.1.1

- CHANGELOG.md
- src/fixes/node-fixes/class-smart-quotes-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-smart-quotes-fix-test.php
Adds a non-breaking space between adjacent primary and secondary quote marks.
> Add a space between adjacent primary and secondary quotes

- composer.json
> Use PHPUnit 7.x where possible

- CHANGELOG.md
- src/fixes/node-fixes/class-smart-fractions-fix.php
- tests/fixes/node-fixes/class-smart-fractions-fix-test.php
`50/50` is most likely not meant as a fraction
> Don't treat "fractional" values equal to 1 as fractions

- CHANGELOG.md
- src/fixes/node-fixes/class-smart-quotes-fix.php
- tests/class-php-typography-test.php
> Fix smart quotes replacement sometimes resulting in invalid unicode sequences

- CHANGELOG.md
- src/class-settings.php
- src/fixes/node-fixes/class-smart-quotes-fix.php
- tests/class-settings-test.php
- tests/fixes/node-fixes/class-smart-quotes-fix-test.php
> Make smart quotes exceptions adjustable

- CHANGELOG.md
- src/diacritics/en-US.json
> Release 6.2.2

- CHANGELOG.md
- src/class-u.php
- src/fixes/class-default-registry.php
- src/fixes/token-fixes/class-smart-dashes-hyphen-fix.php
- tests/class-php-typography-test.php
- tests/fixes/token-fixes/class-smart-dashes-hyphen-fix-test.php
- Uses real Unicode hyphen character instead of hyphen-minus.
- Refactors smart dashes to separate token fix.
> Use real Unicode hyphen

- CHANGELOG.md
Adds CHANGELOG entries for 6.4.0 and 6.3.1 in preparation for the release of 6.4.0.
> Release 6.4.0

- CHANGELOG.md
- src/class-settings.php
- src/fixes/node-fixes/class-smart-ordinal-suffix-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-smart-ordinal-suffix-fix-test.php
_Bugfix_: Parts of hyphenated words should not be detected as Roman numerals anymore.
> Release 6.4.1

- .travis.yml
Run test coverage on PHP 7.3 now.
> Run tests on PHP 7.3

- src/settings/class-dash-style.php
- tests/class-php-typography-test.php
- tests/class-settings-test.php
- tests/fixes/node-fixes/class-dash-spacing-fix-test.php
> Add a new international dash style with no hair spaces

- src/class-settings.php
- src/fixes/class-default-registry.php
- src/fixes/node-fixes/class-smart-area-units-fix.php
- tests/class-php-typography-test.php
- tests/class-settings-test.php
- tests/fixes/class-default-registry-test.php
- tests/fixes/node-fixes/class-smart-area-units-fix-test.php
> Add smart area and volume units

- CHANGELOG.md
- phpunit.xml
- src/fixes/node-fixes/class-smart-dashes-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-smart-dashes-fix-test.php
> Use non-breaking hyphen more often

- CHANGELOG.md
- src/fixes/node-fixes/class-numbered-abbreviation-spacing-fix.php
- src/fixes/node-fixes/class-process-words-fix.php
- src/fixes/node-fixes/class-single-character-word-spacing-fix.php
- src/fixes/node-fixes/class-smart-ellipses-fix.php
- src/fixes/node-fixes/class-smart-exponents-fix.php
- src/fixes/node-fixes/class-smart-marks-fix.php
- src/fixes/node-fixes/class-smart-ordinal-suffix-fix.php
- src/fixes/node-fixes/class-style-caps-fix.php
- src/fixes/node-fixes/class-style-initial-quotes-fix.php
- src/fixes/node-fixes/class-style-numbers-fix.php
- src/settings/class-quote-style.php
- tests/class-text-parser-test.php
- tests/fixes/token-fixes/class-hyphenate-fix-test.php
Update CHANGELOG and apply minor clean-ups.
> Release 6.5.0

- .travis.yml
- CHANGELOG.md
- phpcs.xml
- src/class-php-typography.php
- src/fixes/node-fixes/class-smart-quotes-fix.php
- tests/class-php-typography-test.php
- Adds PHP 7.4 compatibility.
- Adds some additional hyphenation tests.
- Makes parsing more robust in case of invalid DOMDocuments being returned.
- Fixes PHPCS rules after a recent change in WPCS.
> Release 6.5.2

- .scrutinizer.yml
- CHANGELOG.md
- src/diacritics/de-DE.json
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-smart-diacritics-fix-test.php
- Removes ambiguous "blase => blasé" entry from German diacritics file.
- Adds CHANGELOG for 6.5.3.
> Release 6.5.3

- CHANGELOG.md
> Release 6.6.0

- src/class-php-typography.php
- src/class-re.php
- src/fixes/class-default-registry.php
- src/fixes/class-registry.php
- src/fixes/node-fixes/class-style-hanging-punctuation-fix.php
- src/fixes/token-fixes/class-wrap-urls-fix.php
- tests/class-php-typography-test.php
- tests/fixes/node-fixes/class-style-hanging-punctuation-fix-test.php
- tests/fixes/token-fixes/class-wrap-urls-fix-test.php
> Additional SonarCloud fixes

- src/text-parser/class-token.php
- tests/benchmarks/class-html-parser-bench.php
- Reduced the number of `return` statements.
- Adds `$id` and `$val` to the exception messages.
> Clean up Token class
