mundschenk-at/php-typography

.scrutinizer.yml, CHANGELOG.md, src/class-settings.php, src/class-u.php
- Scrutinizer configuration updated.
- Signature for `Settings::set_smart_quotes_*` was missing the `Quotes` type as a possibility.
=> Release 6.1.2

CHANGELOG.md, src/fixes/node-fixes/class-space-collapse-fix.php, tests/class-php-typography-test.php, tests/fixes/node-fixes/class-space-collapse-fix-test.php
Fixes &Aring; (resulted in empty nodes due to a missing `u` flag).
=> Release 6.1.3

CHANGELOG.md, composer.json, src/fixes/node-fixes/class-smart-fractions-fix.php, tests/class-php-typography-test.php, tests/fixes/node-fixes/class-smart-fractions-fix-test.php
_Bugfix_: Smart fractions were not matched correctly if the were followed by a comma (i.e. `1/4,`).
=> Fix smart fractions followed by a comma (parity with 6.1.4)

src/class-settings.php, src/fixes/node-fixes/class-unit-spacing-fix.php, tests/class-settings-test.php, tests/fixes/node-fixes/class-unit-spacing-fix-test.php
Problems:
- Monetary (and other) symbols are not word characters, therefore `\b` won't match.
- Custom units were insufficiently escaped (e.g. `/` was left as-is).
Solution: 
- Instead of trying to match a standard word boundary, we now check for following non-word characters or the end of the string. Fixes #93.
- Custom units are now escaped via `preg_quote`.
=> Refactor unit spacing

src/fixes/node-fixes/class-smart-ordinal-suffix-fix.php, tests/fixes/node-fixes/class-smart-ordinal-suffix-fix-test.php
This PR adds supports
- French (1<sup>ère</sup>) and "Latin" (1<sup>o</sup>) ordinal numbers to the Smart Ordinals feature.
- Roman numerals (with French or Latin suffixes, e.g. XIX<sup>ème</sup>).
The matching rules are permissive and besides Roman numeral matching, no validation is performed to see if the numbers actually agree with the found suffix. This fixes #91.
=> Add support for French and "Latin" ordinal suffixes

CHANGELOG.md, src/fixes/node-fixes/class-dewidow-fix.php, src/fixes/node-fixes/class-style-caps-fix.php, tests/class-php-typography-test.php, tests/fixes/node-fixes/class-style-caps-fix-test.php
_Bugfix_: The Unicode hyphen character (`‐`) is recognized as a valid word combiner.
=> Release 6.4.2

CHANGELOG.md, src/class-settings.php, src/fixes/node-fixes/class-smart-ordinal-suffix-fix.php, tests/class-settings-test.php, tests/fixes/node-fixes/class-smart-ordinal-suffix-fix-test.php
- Single-letter Roman numbers are ignored, except for `I`, `V`, and `X` (still problematic for Italian, though, because of `Io` at the start of a sentence).
- Roman numeral matching is disabled unless it's first enabled with the new method `Settings::set_smart_ordinal_suffix_match_roman_numerals()`.
Fixes #103.
=> Refactor Roman numeral ordinals

src/fixes/node-fixes/class-smart-quotes-fix.php, tests/class-php-typography-test.php, tests/fixes/node-fixes/class-smart-quotes-fix-test.php
`'60s` and `'80er` are now rendered with an apostrophe. Fixes #107.
=> Apostrophe for decades

src/class-php-typography.php, src/class-settings.php, src/class-u.php, src/fixes/node-fixes/class-dewidow-fix.php, src/fixes/node-fixes/class-french-punctuation-spacing-fix.php, src/fixes/node-fixes/class-smart-dashes-fix.php, src/fixes/node-fixes/class-smart-fractions-fix.php, src/fixes/node-fixes/class-smart-quotes-fix.php, src/fixes/node-fixes/class-unit-spacing-fix.php, src/settings/class-dash-style.php, src/settings/class-quote-style.php, tests/class-php-typography-test.php, tests/class-php-typography-testcase.php, tests/class-settings-test.php, tests/fixes/node-fixes/class-smart-quotes-fix-test.php
- Adds general character remapping framework
- Deprecates `Settings:: set_true_no_break_narrow_space()` and `Settings::no_break_narrow_space()`
- Updates the fixes to use the new framework consistently.
Fixes #99.
=> Add general character remapping framework

CHANGELOG.md, src/fixes/node-fixes/class-smart-area-units-fix.php, tests/fixes/node-fixes/class-smart-area-units-fix-test.php, tests/fixes/node-fixes/class-unit-spacing-fix-test.php
The smart area and volume units fix now handles missing whitespace as well (e.g. `5m2` is transformed into `5 m²`).
=> Release 6.5.1

.github/workflows/ci.yml, .gitignore, README.md, composer.json, phpbench.json, phpcs.xml, sonar-project.properties
- Requires at least PHP 7.2.0.
- Switches to GitHub Actions and SonarCloud for CI.
- Updates `composer.json` for Composer 2.x.
=> Update CI workflow & Composer requirements

.github/workflows/ci.yml, README.md, composer.json, phpcs.xml, src/class-strings.php
- Updates minimum PHP version to 7.4.
- Enables native `mb_str_split`.
=> Require at least PHP 7.4

composer.json, src/bin/class-pattern-converter.php, src/class-strings.php, src/class-u.php, src/fixes/node-fixes/class-style-caps-fix.php, tests/class-settings-test.php, tests/class-strings-test.php, tests/class-testcase.php
- Deprecates `Strings::uchr`.
- Properly detects ASCII strings (we were really always using UTF-8 before!).
- Use the native PCRE unicode character class `\p{Lu}` to detect upper-case letters.
=> Use new PHP unicode features

.github/workflows/ci.yml
- Updates `actions/checkout` and `actions/cache` to `v4`.
- Does not mark PHP 8.3 as "experimental" anymore.
=> Update GItHub actions and CI workflow

src/class-dom.php, tests/class-dom-test.php, tests/class-php-typography-test.php, tests/fixes/node-fixes/class-node-fix-testcase.php, tests/fixes/node-fixes/class-smart-quotes-fix-test.php
- Fixes #142. 
- Fixes #134.
- Renames `DOM::get_adjacent_chr` to `DOM::get_adjacent_character`.
- Refactors the various `DOM::get_*_textnode` methods to allow for different acceptable nodes.
- Also adds some tests.
=> Handle specific elements when looking for adjacent characters

src/class-dom.php, src/fixes/node-fixes/class-dewidow-fix.php, src/fixes/node-fixes/class-french-punctuation-spacing-fix.php, src/fixes/node-fixes/class-single-character-word-spacing-fix.php, src/fixes/node-fixes/class-smart-quotes-fix.php, src/fixes/node-fixes/class-space-collapse-fix.php, src/fixes/node-fixes/class-style-hanging-punctuation-fix.php, src/fixes/node-fixes/class-style-initial-quotes-fix.php, src/fixes/token-fixes/class-hyphenate-fix.php, tests/class-dom-test.php
- Removes unused or obsolete methods from class `PHP_Typography\DOM`:
* `::get_block_parent_name`
* `::get_previous_textnode`
* `::get_next_textnode`
* `::get_last_textnode`
- Adds type declarations to all methods.
- Renames `::get_prev_chr` to `::get_previous_character`.
- Renames `::get_next_chr` to `::get_next_character`.
- Cleans up private methods.
=> Refactor `DOM` API

composer.json, src/class-hyphenator.php, src/exceptions/class-invalid-file-exception.php, src/exceptions/class-invalid-hyphenation-pattern-file-exception.php, src/exceptions/class-invalid-json-exception.php, src/hyphenator/class-cache.php, src/hyphenator/class-trie-node.php, tests/class-hyphenator-test.php, tests/fixes/token-fixes/class-hyphenate-fix-test.php, tests/hyphenator/class-cache-test.php
- Removes unnecessary default values from methods.
- Adds type declarations.
- Extracts new method `::read_patterns_from_file` method.
=> Refactor `Hyphenator` and its dependancies

src/fixes/node-fixes/class-style-caps-fix.php, tests/fixes/node-fixes/class-style-caps-fix-test.php
- Allows detection of caps at the beginning of compound words. FIxes #174.
=> Allow detection of caps at the beginning of compound words

src/class-settings.php, src/class-strings.php, tests/class-php-typography-test.php, tests/class-settings-test.php, tests/class-strings-test.php
- Uses `sha256` instead of `md5` for generating hashes.
- Adds type declarations.
- Removes legacy string parsing (using `Strings::maybe_split_parameters` or direct regular expression) for settings expecting an `array`. Fixes #100.
- Removes the now unused static method `Strings::maybe_split_parameters`.
=> Minor improvements for the Settings class

src/class-settings.php, tests/class-settings-test.php
- Removes all trivial `set_*` methods and replaces them with the `__call` magic method.
- Changes the semantics of setting out-of-bounds integer values, instead of silently resetting to the default value, a `OutOfRangeException` is thrown.
=> Refactor Settings

.github/workflows/ci.yml
- Explicitly uses `composer run-script`.
- Uses `composer update` instead of `composer install` as there is no `composer.lock` file in the repository.
- Cleans up the Spellchecking workflow.
=> Improve GHA workflow

src/class-settings.php, src/settings/class-dash-style.php, src/settings/class-quote-style.php, tests/class-settings-test.php, tests/class-testcase.php
Makes sure that the `Settings` object is fully usable even when `$use_defaults` is set to `false` in the constructor.
=> Fully initialize Settings even when $use_defaults is set to false

src/bin/class-pattern-converter.php
Use more specific exception classes instead of `RuntimeException`.
=> Use more specific exceptions in pattern converter

src/class-php-typography.php, src/class-settings.php, src/fixes/class-default-registry.php, src/fixes/class-registry.php, src/fixes/node-fixes/class-unicode-remapping-fix.php, tests/class-php-typography-test.php, tests/class-settings-test.php, tests/fixes/node-fixes/class-unicode-remapping-fix-test.php
- Removes the hard-coded call to `Settings::apply_character_mapping` from `PHP_Typography::process_textnodes_internal`.
- Adds new fix groups `PRE_PROCESSING` and `POST_PROCESSING` to `Registry`.
- Adds new `Unicode_Remapping_Fix` token fix.
=> Replace hard-coded character remapping with new post-processing fix
